joint_pose:
  $(arg arm_id)_joint1: -1.3
  $(arg arm_id)_joint2: 1.6
  $(arg arm_id)_joint3: 1.6
  $(arg arm_id)_joint4: -2.1
  $(arg arm_id)_joint5: 1.57
  $(arg arm_id)_joint6: 1.62
  $(arg arm_id)_joint7: -0.81
